# Generated by scripts/generate-integrations.py; do not edit directly.
set -l color00 '#1C1D19'
set -l color01 '#E89189'
set -l color02 '#A8C486'
set -l color03 '#E8BD59'
set -l color04 '#E8BD59'
set -l color05 '#C7A0D3'
set -l color06 '#86C5B5'
set -l color07 '#C9C1AC'
set -l color08 '#ABA08A'

# Preserve quoted user options; replace only the suffix added by this integration.
if set -q __mooni_dark_fzf_suffix
    set -gx FZF_DEFAULT_OPTS (string replace -- "$__mooni_dark_fzf_suffix" '' "$FZF_DEFAULT_OPTS")
end
set -g __mooni_dark_fzf_suffix " --color=bg+:#49402B,bg:$color00,spinner:$color06,hl:$color04 --color=fg:#EAE4D3,header:$color04,info:$color02,pointer:$color06 --color=marker:$color06,fg+:#EAE4D3,prompt:$color02,hl+:$color04"
set -gx FZF_DEFAULT_OPTS "$FZF_DEFAULT_OPTS$__mooni_dark_fzf_suffix"
